### ISSUE TITLE
Добавить опцию для отключения проверки сертификата при скачивании архива

### ISSUE THREAD

**Issue by jenya87** [liquetsoft/fias-laravel#10]
Здравствуйте. При запуске команды ```liquetsoft:fias:install``` (Laravel 5.8, Windows 7, версия пакета - последняя) возникает ошибка 
```  
  Liquetsoft\Fias\Component\Exception\PipeException  : Error while running Liquetsoft\Fias\Comp
onent\Pipeline\Task\DownloadTask task: Error while downloading 'https://fias-file.nalog.ru/Expor
tDownloads?file=XXXXXXX-5f9b-4585-aaeb-XXXXXXX': SSL certificate problem: unable to get lo
cal issuer certificate

```
Версия php 7.2.31 (поставил 7.2, тк на  7.3.5 скачивался 9 гиговый архив - без ошибки, но не распаковывался, добавление в файл AppServiceProvider в метод register команды замены распаковщика не помогло)

Расширение openssl включено. Подскажите, в чём беда! Спасибо!

**Comment by marvin255** [comment]
Добрый день. Весьма вероятно, что ваш curl не может проверить сертификат для домена `fias-file.nalog.ru`. Более того, учитывая как часто случаются проблемы на стороне ФИАС это может быть связано с самим сертификатом.

Попробуйте проверить методы из этой [статьи](https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate).

Я же со своей стороны добавлю опцию для отключения проверки сертификата, на такие случаи.

**Comment by jenya87** [comment]
Спасибо за ответ! Последовал рекомендациям из данной вами ссылки (про добавление cacert.pem), в результате другая теперь ошибка:
```php artisan liquetsoft:fias:install
Installing full version of FIAS.
  Liquetsoft\Fias\Component\Exception\PipeException  : Error while running Liquetsoft\Fias\Comp
onent\Pipeline\Task\InformFullTask task: Exception has been thrown by the target of an invocatio
n.
  at C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\Pipeline\Pipe\ArrayPipe.php
:141
    137|         ]);
    138|
    139|         $this->proceedCleanup($state);
    140|
  > 141|         throw new PipeException($message, 0, $e);
    142|     }
    143|
    144|     /**
    145|      * Обработка завершения задачи.
�ения задачи.
�ачи.

  Exception trace:
  1   Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe::proceedException(Object(Liquetsoft\Fias
\Component\Pipeline\State\ArrayState), Object(Liquetsoft\Fias\Component\Pipeline\Task\InformFull
Task), Object(SoapFault))
      C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\Pipeline\Pipe\ArrayPipe.ph
p:72

  2   SoapFault::("Exception has been thrown by the target of an invocation.")
      C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\FiasInformer\SoapFiasInfor
mer.php:42
Please use the argument -v to see more details.
```
Soap включено...
Самое интересное - вернул, как было раньше без cacert.pem, передёрнул apache,  ошибка с сертификатом ушла, зато теперь ошибка, которую я описал выше в этом посте...

















```

**Comment by marvin255** [comment]
А вот это связано уже с сервисом информирования, кажется, он не работает. Эту ошибку `Exception has been thrown by the target of an invocation` возвращает сам сервис информирования. Даже на оф. сайте ошибка: https://fias.nalog.ru/Updates

Я столкнулся с этой же проблемой. Как только сервис информирования заработает и я смогу провести тесты, сразу же выкачу обновления.

**Comment by jenya87** [comment]
Спасибо, буду ждать))

**Comment by jenya87** [comment]
Заработал сервис ФИАС,  запустил установку по artisan команде, но, к сожалению ошибка:
```
php artisan liquetsoft:fias:install
Installing full version of FIAS.
   Liquetsoft\Fias\Component\Exception\PipeException  : Error while running Liquetsoft\Fias\Comp
onent\Pipeline\Task\UnpackTask task: Can't extract 'C:\Apache_htdocs\phonebook\storage\liquetsof
t_fias/archive' to 'C:\Apache_htdocs\phonebook\storage\liquetsoft_fias/extracted'.
  at C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\Pipeline\Pipe\ArrayPipe.php
:141
    137|         ]);
    138|
    139|         $this->proceedCleanup($state);
    140|
  > 141|         throw new PipeException($message, 0, $e);
    142|     }
    143|
    144|     /**
    145|      * Обработка завершения задачи.
�ения задачи.
�ачи.
  Exception trace:
  1   Liquetsoft\Fias\Component\Pipeline\Pipe\ArrayPipe::proceedException(Object(Liquetsoft\Fias
\Component\Pipeline\State\ArrayState), Object(Liquetsoft\Fias\Component\Pipeline\Task\UnpackTask
), Object(Liquetsoft\Fias\Component\Exception\UnpackerException))
      C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\Pipeline\Pipe\ArrayPipe.ph
p:72
  2   Liquetsoft\Fias\Component\Exception\UnpackerException::("Can't extract 'C:\Apache_htdocs\p
honebook\storage\liquetsoft_fias/archive' to 'C:\Apache_htdocs\phonebook\storage\liquetsoft_fias
/extracted'.")
      C:\Apache_htdocs\phonebook\vendor\liquetsoft\fias-component\src\Unpacker\ProcessUnpacker.p
hp:48

  Please use the argument -v to see more details.
```
Вероятно, ошибка с распаковкой, тк бд фиас скачивается полностью.Но я использую php 7.2, с rar extension, extension включён (по phpinfo например если смотреть)
Подскажите пожалуйста, как победить?

**Comment by marvin255** [comment]
Да, всё верно, они в какой-то момент перешли с rar на zip наконец-то. Обновил основную версию компонента до 6 - в ней распаковка zip.

Обновите библиотеку fias-laravel [до версии 4](https://github.com/liquetsoft/fias-laravel/releases/tag/v4.0.0), уберите все замены разрархиватора, чтобы подключался встроенный.

Для точной настройки curl используйте параметр конфигурации `curl_settings`:
```php
//config/liquetsoft_fias.php
'curl_settings' => [
    'CURLOPT_SSL_VERIFYHOST' => 0,
    'CURLOPT_SSL_VERIFYPEER' => 0,
],
