### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rus-ik** [liquetsoft/fias-laravel#12]
Getting error while installing on the latest laravel ^7.0:

bash-4.2$ COMPOSER_MEMORY_LIMIT=-1 composer require liquetsoft/fias-laravel
Using version ^4.0 for liquetsoft/fias-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException 

  File '' for yaml entity registry isn't readable or doesn't exist.

  at vendor/liquetsoft/fias-component/src/EntityRegistry/YamlEntityRegistry.php:32
    28|      */
    29|     public function __construct(string $pathToYaml)
    30|     {
    31|         if (!file_exists($pathToYaml) || !is_readable($pathToYaml)) {
  > 32|             throw new InvalidArgumentException(
    33|                 "File '{$pathToYaml}' for yaml entity registry isn't readable or doesn't exist."
    34|             );
    35|         }
    36|

      +27 vendor frames 
  28  [internal]:0
      Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\Command\InstallCommand::__construct(Object(Illuminate\Foundation\Application))

      +12 vendor frames 
  41  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by marvin255** [comment]
Will check.

**Comment by rus-ik** [comment]
@marvin255 Any updates?

**Comment by marvin255** [comment]
Sorry for delay but I can not reproduce this issue on fresh laravel installation.
Probably you have folder structure different than default. I will publish a commint with deferred loading for yaml file and you will nedd to [publish lib config](https://github.com/liquetsoft/fias-laravel#%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0) and change `registry_yaml` parameter to youra path for `fias_entities.yaml`.

**Comment by marvin255** [comment]
Main component updated.
