### ISSUE TITLE
[FEATURE] Lumen 7 Support

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#13]
При установке на люмен получил проблемы с рефлексией на класс config (с маленькой).
Отключение в app.php регистрации сервис провайдера всё нормализует.

Прошу довести пакет до ума.

**Comment by marvin255** [comment]
От lumen сознательно отказались. Для него нужно делать отдельный пакет хотя бы потому, что `Application` lumen'а не реализует контракт для `Illuminate\Contracts\Foundation\Application`.

И еще много разных и неприятных различий. Основной laravel более предсказуем по комплектации и по доступным методам.

**Comment by h-zone** [comment]
а 7ю версию смотрели?
+ я где-то пробегал мимо не то на гитхабе не то в гугле, что костылём Апп таки сделали.
= хуже чем попробуете не станет ;)
