### ISSUE TITLE
[FEATURE] Добавить в модель свойство connection

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#14]
Фиас сам по себе не маленький, и в больших компаниях его хранят в отдельной БД, да и вообще в другом ЦОДЕ ;)

Прошу добавить в модели `protected $connection;` и в конструкторе/генераторе читать конфиг, какой connection использовать.

Спасибо!

**Comment by marvin255** [comment]
Все же хотел бы предоставлять только описание моделей и данных как таковых, без каких-либо настроек.

Предлагаю унаследовать модели проекта от моделей пакета и переопределить в них `connection`.

**Comment by h-zone** [comment]
Унаследование не прокатит, да просто потому что неудобно.
Пакет сейчас недостаточно конфигурируемый. Стоит дополнить.

**Comment by marvin255** [comment]
Нужно создать модель в целевом проекте, например:
```php

namespace App\Components;

class AddressObject extends \Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\Entity\AddressObject
{
    protected $connection = 'connection-name';
}
```

Опубликовать конфигурацию библиотеки в проект командой:
```bash
php artisan vendor:publish --provider="Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\LiquetsoftFiasBundleServiceProvider"
```

Подменить реализацию для сущности в `config/liquetsoft_fias.php`:
```php
'entity_bindings' => [
    'AddressObject' => \App\Components\AddressObject::class,
   // ....
],
```

Рекомендую подменить все модели, которые предоставляет библиотека на наследование. Такой подход выбран не случайно: сложно предсказать, что именно потребуется в проекте (события, отношения с другими моделями, дополнительные геттеры/сеттеры, скоупы и т.д.). Если добавлять все подряд, то учесть все нюансы не удастся, а модели будут наполнены лишней логикой. В итоге библиотека предоставляет легкие модели, в которых просто размечена структура таблицы.
