### ISSUE TITLE
[BUG] непонятная бага при первичной заливке

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#18]
`php artisan liquetsoft:fias:install`

получаю

```
Installing full version of FIAS.
   Liquetsoft\Fias\Component\Exception\PipeException
Error while running Liquetsoft\Fias\Component\Pipeline\Task\DownloadTask task: Error while downloading 'https://fias-file.nalog.ru/ExportDownloads?file=a8208b61-5ba3-4917-a5cb-032594e2fc7a': HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
```

wget забрал файл нормально.

если вы знаете ответ, то прошу скорейше поделиться информацией.

заранее спасибо!

**Comment by h-zone** [comment]
при этом, по времени, вываливается раномно из скачивания.

**Comment by marvin255** [comment]
Это ошибка [curl](https://github.com/liquetsoft/fias-component/blob/master/src/Downloader/CurlDownloader.php#L45), не связанная с пакетом. Нужно либо искать проблему либо в в коннекте до серверов ФИАС, .либо в curl, например, [вот тут](https://github.com/curl/curl/issues/3527) что-то подобное.
