### ISSUE TITLE
RarArchive php 7.3

### ISSUE THREAD

**Issue by Serokuz22** [liquetsoft/fias-laravel#2]
На гитхабе уже есть https://github.com/cataphract/php-rar с поддержкой 7.3 но в pecl нет, может кто нибудь скомпилирует? Долбанный rar впереди планеты всей

**Comment by Serokuz22** [comment]
Или лучше перепишите распаковку через exec

**Comment by marvin255** [comment]
С rar расширением ничем не могу помочь. Распаковка через консольную команду добавлена в v2.1.0(#3). Пример:
```php
// в AppServiceProvider::register
$this->app->singleton(\Liquetsoft\Fias\Component\Unpacker\Unpacker::class, function ($app) {
    $commandTemplate = new \Liquetsoft\Fias\Component\Process\TemplateProcess('unrar x {{source}} {{destination}}');
    return new \Liquetsoft\Fias\Component\Unpacker\ProcessUnpacker($commandTemplate);
});
```
