### ISSUE TITLE
Пакет очень медленно вставляет данные в бд.

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#20]
Ещё раз приветствую!
Пакет за 3 часа вставил только 140 000 адресов.
Это нормально?
БД и Сайт = 2 гостевые ОС на одном Хосте.
Если это не нормально, то вопрос, - занимались ли вы производительностью, и что можете посоветовать для поднятия этой производительности ?

**Comment by marvin255** [comment]
Из оптимизаций на стороне библиотеки в основном только bulk insert. Распараллеливание вставки в одну таблицу, к сожалению, не слишком эффективно. Индексы сокращены до минимума.

* Переход с hdd на ssd дает огромный прирост, которого не достичь другими оптимизациями.
* Нативные поля для uuid дают неплохой прирост (laravel к сожалению создает строку вместо них).
* Тонкие настройки конкретно вашей бд и системы сильно помогают.
* Префильтрация (если не нужны все города), отказ о вставки ненужных данных (terrifnsfl и т.д. не всем нужны).
* Переход от бд к elasticsearch, если это допустимо.

В целом советую отталкиваться от нужд проекта.

Для примера, на моем тестовом VPN с SSD, в postgres, таблица AddressObject импортируется за два с половиной часа целиком.
