### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mbarev** [liquetsoft/fias-laravel#21]
Процесс установки заканчивается "слишком быстро".

Артисан репортует о завершении установки, однако в БД записей не появляется. 
Подскажите пожалуйста куда копать?

`Installing full version of FIAS.
Full version of FIAS installed after 984.4026 s.
`

**Comment by mbarev** [comment]
Выяснилось следующее:
ФИАС поменял структуру архива, файлы ADDROBJ, HOUSES и тд попадают в подпапку "00", которая не индексируется сборщиком фалов.

Как вариант - индексировать не только `EXTRACT_TO_FOLDER_PARAM` но и вложенные папки.

**Comment by marvin255** [comment]
Буквально на днях тестировал для нового релиза и тут такое вот. При этом совершенно не понятно где и как выкладываются оповещения об изменениях. Проверим, поправим.

**Comment by marvin255** [comment]
Еще и скорость ограничили на скачивание.

**Comment by marvin255** [comment]
Быстрый фикс - https://github.com/liquetsoft/fias-component/releases/tag/v6.4.0
Если успею скачать сегодня, то проверю.
