### ISSUE TITLE
[BUG] Unique violation: 7 ERROR....

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#23]
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "fias_laravel_normative_document_pkey"

полный дамп от 04.авг.2020

и да, скорость даже на ссд на xeon E3-1220, вставки полного дампа никак не 2 часа. а часов 20, плюс-минус.
только эта задача, не виртуалка, дебиан. производительность ни к чёрту.

по сабжу прошу проверить. сомнительная ошибка.

**Comment by marvin255** [comment]
Нужен полный дог ошибки. Такое возможно - качество выгрузки оставляет желать лучшего.

20+ часов - это весь ФИАС, а это, на секунду, 70ГБ в xml представлении. Повторюсь, что оптимизации должны проводиться под проект: например, можно не писать исторические данные по адресам, не грузить квартиры и участки по ненужным регионам, использовать elastic, для postgres прекрасно помогают unlogged таблицы и т.д.

**Comment by h-zone** [comment]
Полный дамп базы не встаёт.
Голая лара с вашим бандлом.
1.8гб лог  ошибок. за 28 часов работы.

Могу точно сказать, что нормативные документы в начале ошибок по уникальному pkey не встают (кроме pkey вставляемые данные __могут__ отличаться), и в конце лога объект stead не встаёт.

Всё. Алес. Ищу альтернативу. Спасибо за отличный Продукт ;) и потерянные 2 недели.
