### ISSUE TITLE
[BUG] ошибка при апдейте

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#28]
```
Updating FIAS.

   Liquetsoft\Fias\Component\Exception\PipeException

  Error while running Liquetsoft\Fias\Component\Pipeline\Task\DataUpsertTask task: Can't update or insert entity in storage.

  at vendor/liquetsoft/fias-component/src/Pipeline/Pipe/ArrayPipe.php:141
    137|         ]);
    138|
    139|         $this->proceedCleanup($state);
    140|
  > 141|         throw new PipeException($message, 0, $e);
    142|     }
    143|
    144|     /**
    145|      * Обработка завершения задачи.

      +35 vendor frames
  36  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```
опять not null violation

вопрос.
как вы отслеживаете изменения структуры таблиц?

**Comment by marvin255** [comment]
До версии 6 - в ручном режиме по файлу с документацией, который обновлялся много лет назад, судя по всему.

В версии [v6.0.0](https://github.com/liquetsoft/fias-laravel/releases/tag/v6.0.0) добавили анализ [XSD схем](https://github.com/liquetsoft/fias-component/tree/master/resources/xsd), которые поставляются вместе с новыми сборками ФИАС.

Путем нехитрой склейки [своих данных](https://github.com/liquetsoft/fias-component/blob/master/resources/fias_entities_default.php) и данных из схем получаем [результирующий массив](https://github.com/liquetsoft/fias-component/blob/master/resources/fias_entities.php), из которого и генерируются все модели в библиотеке.

К сожалению, пришлось менять мажорную версию из-за того, что ФИАС перестал предоставлять две таблицы, заменив их enum.

Проблему с повторяющимися первичными ключами для `NormativeDocument` это не решает. Как я уже и говорил - в выгрузке действительно есть эти дубли. Зато вся остальная структура вполне соответствует поставляемым данным.

**Comment by h-zone** [comment]
Ваш ответ не решает not null violation при апдейте

**Comment by marvin255** [comment]
Это в версии 6 повторяется тоже?

**Comment by h-zone** [comment]
> 
> 
> Это в версии 6 повторяется тоже?

сорян. только счас добрался до хаба.

ответ - да.

новая ошибка (в конфе ничего не менялось)
```
   Liquetsoft\Fias\Component\Exception\PipeException

  Error while running Liquetsoft\Fias\Component\Pipeline\Task\DownloadTask task: Error while downloading 'https://fias.nalog.ru/DownloadUpdates?file=fias_delta_xml.zip&version=20200818': transfer closed with 255749495 bytes remaining to read

  at vendor/liquetsoft/fias-component/src/Pipeline/Pipe/ArrayPipe.php:141
```

**Comment by h-zone** [comment]
в догонку:
скачивать не даёт по всей видимости из-за юзер-агента.
подставьте браузер в качестве юзер агента, ибо из браузера ссылку обновления отдаёт файлом.

**Comment by marvin255** [comment]
Ошибка при скачивании ни на одной площадке не моделируется.
Юзер-агент можно задать через конфиг `curl_settings`. [Подробнее](https://www.php.net/manual/ru/function.curl-setopt.php).

**Comment by marvin255** [comment]
Ошибок при обновлении не наблюдаю. Рекомендую стереть все таблицы модуля и создать из миграций версии 6 заново.
