### ISSUE TITLE
[FEATURE] опция в конфиг

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#29]
- Сделайте пожалуйста опцию в конфиг "не удалять скаченный апдейт",  соответственно с обработчиком.

- Так же прошу дать возможность не только писать логи, но и выводить их на экран. Нужно, чтобы ловить на каком этапе сломалось, чтобы не рыть весь лог на несколько гигабайт. Да и при отработке кроном ловить stdout удобно с тем же кейзом.

- Необходимо что-то с логированием сделать. Слишком детальный лог === слишком большой лог. Нужно знать в какой таблице, какая запись не встала, и если следующая запись с теми же самыми ошибками, в ту же таблицу - не повторять детали. просто сказать какая строка/ид строки не встало.
А то, понимаешь, лог выглядит, как буд-то у вас есть парсер и корректор по логу... а у нас нет.... кстати.

**Comment by marvin255** [comment]
`Сделайте пожалуйста опцию в конфиг "не удалять скаченный апдейт", соответственно с обработчиком.` - https://github.com/liquetsoft/fias-laravel/issues/30

**Comment by marvin255** [comment]
`Так же прошу дать возможность не только писать логи, но и выводить их на экран.` - https://github.com/liquetsoft/fias-laravel/issues/31 хотя не уверен, что получится для параллельных процессов его правильно сбиндить, но рассмотрим.

**Comment by marvin255** [comment]
`Нужно знать в какой таблице, какая запись не встала, и если следующая запись с теми же самыми ошибками, в ту же таблицу - не повторять детали. просто сказать какая строка/ид строки не встало.` - рассмотрим вариант не записывать повторяющиеся ошибки, но не уверен, что это будет верно.

**Comment by marvin255** [comment]
`А то, понимаешь, лог выглядит, как буд-то у вас есть парсер и корректор по логу... а у нас нет.... кстати.` - [ELK](https://www.elastic.co/what-is/elk-stack), кибана замечательно группирует логи по pipeline_id и прекрасно работает с поиском данных.

**Comment by h-zone** [comment]
> 
> 
> `Нужно знать в какой таблице, какая запись не встала, и если следующая запись с теми же самыми ошибками, в ту же таблицу - не повторять детали. просто сказать какая строка/ид строки не встало.` - рассмотрим вариант не записывать повторяющиеся ошибки, но не уверен, что это будет верно.

как отключаемая опция - норм зайдёт
