### ISSUE TITLE
[BUG] всё равно не качает. Идеи есть?

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#39]
**Ошибка**
```
   Liquetsoft\Fias\Component\Exception\DownloaderException

  Error while downloading 'https://fias.nalog.ru/DownloadUpdates?file=fias_xml.zip&version=20200915': transfer closed with 9916583367 bytes remaining to read

  at vendor/liquetsoft/fias-component/src/Downloader/CurlDownloader.php:45
    41|         [$res, $httpCode, $error] = $this->curlDownload($requestOptions);
    42|         fclose($fh);
    43|
    44|         if ($res === false) {
  > 45|             throw new DownloaderException("Error while downloading '{$url}': {$error}");
    46|         } elseif ($httpCode !== 200) {
    47|             throw new DownloaderException("Url '{$url}' returns status: {$httpCode}");
    48|         }
    49|     }

      +15 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Причина**
По умолчанию, курл сохраняет ответ сервера в памяти. Таким образом мы упираемся в потолок настройки выделения памяти в `php.ini`.

У вас есть опция CURLOPT_FILE, но не помогает решению.
Я невдупляю, где проблема.

Ни на одной виртуалке не работает.
Ошибка одинаковая.

Поделитесь инфой о сетевой инфраструктуре на ваших мощностях. Может в них проблема, хотя не уверен, что проблема в них.

При всём этом, браузер высасвает файл на ура и с первой попытки.

**Comment by h-zone** [comment]
это пробовали вместо курла?
http://docs.guzzlephp.org/en/latest/

**Comment by marvin255** [comment]
Проблема не в оперативной памяти, и не в ресурсах - там самая экономная потоковая запись в файл, без промежуточного сохранения всего объема.

Скорее всего проблема в соединении между целевым сервером и сервером ФИАС. Вот, [например](https://community.developers.refinitiv.com/questions/16661/curl-18-transfer-closed-with-803828224-bytes-remai.html) или [вот](https://stackoverflow.com/a/1848947/4693620), или [вот](https://justrocketscience.com/post/php_guzzle_bug/). Не могу сказать какая именно настройка поможет в вашем случае, тем не менее они все передаются через конфиги.

Браузер у вас на другой машине скорее всего, с другими настройками. Если же вы в браузере можете скачать, а через php с той же машины - нет, то проблема явно решается одной из настроек по приведенным выше ссылкам.

Guzzle под капотом использует тот же [curl](https://github.com/guzzle/guzzle/blob/33ddb580d0d88242fa9d597b4715f5f89c5e56a1/src/Utils.php#L93).

**Comment by h-zone** [comment]
не помогло.

**Comment by h-zone** [comment]
встала база.
оказалось, что проблема только в сайте налога.ру

но есть опять косяк - не встала версия.
