### ISSUE TITLE
[FEATURE] Работа с версиями ФИАС

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#41]
Собственно из 5 виртуалок, только 3 отработали по вставке с нуля за выходные.
Однако ни один таск не вставил Версию, и в логах по `Version` ни слова нет.

Есть предложение, как обойти проблему.

1. `версия` встаёт перед вставкой БД, но  с флагом `is_failed = true`
2. опция в конфиг - "удалять версию при исключении или неудачной вставке", или оставлять для истории.
4. чистка prune таких записей отдельной командой.

**Comment by marvin255** [comment]
Проблемы после `liquetsoft:fias:install` или после `liquetsoft:fias:install_from_folder`?

**Comment by marvin255** [comment]
https://github.com/liquetsoft/fias-laravel/releases/tag/v6.6.0 - команда для принудительной установки версии.

`liquetsoft:fias:install_from_folder` и `liquetsoft:fias:update_from_folder` сами по себе версии не устанавливают потому, что им неоткуда ее взять.

Для `liquetsoft:fias:install` и `liquetsoft:fias:update` проблемы не наблюдаю.

**Comment by h-zone** [comment]
`liquetsoft:fias:install`
скачало и вставило
распараллеливание сильно помогло.
версию вставлял руками.
