### ISSUE TITLE
[BUG] новый баг после обновления

### ISSUE THREAD

**Issue by h-zone** [liquetsoft/fias-laravel#44]
`liquetsoft:fias:update`
```
Updating FIAS.

   Liquetsoft\Fias\Component\Exception\PipeException

  Error while running Liquetsoft\Fias\Component\Pipeline\Task\InformDeltaTask task: Wrong url format:

  at vendor/liquetsoft/fias-component/src/Pipeline/Pipe/ArrayPipe.php:141
    137|         ]);
    138|
    139|         $this->proceedCleanup($state);
    140|
  > 141|         throw new PipeException($message, 0, $e);
    142|     }
    143|
    144|     /**
    145|      * Обработка завершения задачи.

      +23 vendor frames
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```
лог вложен

[laravel.log](https://github.com/liquetsoft/fias-laravel/files/5298096/laravel.log)

**Comment by h-zone** [comment]
моё мнение: надо внедрить систему подсказок о причинах и/или вариантах происхождения ошибок.
для этого достаточно проанализировать этот раздел issue и сделать мелкий справочник...

**Comment by marvin255** [comment]
С этой я тоже столкнулся. Вот тут ситуация явно исключительная. Почему-то для последних версий перестали ссылки на файлы присылать. Не знаю с чем это связано. Вероятно на стороне фиас проблемы. 

Сегодня ссылки вижу.
