### ISSUE TITLE
[BUG] Initial installation error

### ISSUE THREAD

**Issue by rus-ik** [liquetsoft/fias-laravel#48]
# php artisan liquetsoft:fias:install
Installing full version of FIAS.

   Liquetsoft\Fias\Component\Exception\PipeException 

  Error while running Liquetsoft\Fias\Component\Pipeline\Task\TruncateTask task: Can't truncate storage.

  at vendor/liquetsoft/fias-component/src/Pipeline/Pipe/ArrayPipe.php:142
    138▕         ]);
    139▕ 
    140▕         $this->proceedCleanup($state);
    141▕ 
  ➜ 142▕         throw new PipeException($message, 0, $e);
    143▕     }
    144▕ 
    145▕     /**
    146▕      * Обработка завершения задачи.

      +29 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by marvin255** [comment]
There must be more frames. I need other frames for debug too.
