### ISSUE TITLE
[FEATURE] Add config option to specify a separate DB for fias

### ISSUE THREAD

**Issue by rus-ik** [liquetsoft/fias-laravel#49]
Is it hard to add the config options for 'database' and 'schema'?

**Comment by marvin255** [comment]
The best solution for the `database` property in models is inheritance. Just create all models that you need in projects and set up needed database. Example:
```php
namespace App\Models;

use Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\Entity\ActualStatus as FiasActualStatus;

class ActualStatus extends FiasActualStatus
{
    protected $connection = 'sqlite';
}
```
Than replace the model in config:
```php
// config/liquetsoft_fias.php
'entity_bindings' => [
    // ...other data
    'ActualStatus' => \App\Models\ActualStatus::class,
],
```
Not sure what do you mean under the `schema` option.
