### ISSUE TITLE
Не работает миграция в отдельную базу из-за этой строчки

### ISSUE THREAD

**Issue by edwardproff** [liquetsoft/fias-laravel#53]
https://github.com/liquetsoft/fias-laravel/blob/0e63ab8dec24241119bc7b56e6cd92657d012afb/src/Migration/2019_09_03_144400_fias_laravel_room.php#L53

**Comment by edwardproff** [comment]
и этой

https://github.com/liquetsoft/fias-laravel/blob/0e63ab8dec24241119bc7b56e6cd92657d012afb/src/Migration/2019_09_03_144400_fias_laravel_house.php#L58

**Comment by marvin255** [comment]
Не могли бы вы показать какая именно ошибка возвращается от базы данных?

**Comment by edwardproff** [comment]
Migrating: 2019_09_03_144400_fias_laravel_house

   Illuminate\Database\QueryException 

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fias_test.fias_laravel_house' doesn't exist (SQL: ALTER TABLE fias_laravel_house PARTITION BY KEY() PARTITIONS 4;)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕ 

  • A table was not found: You might have forgotten to run your migrations. You can run your migrations using `php artisan migrate`. 
    https://laravel.com/docs/master/migrations#running-migrations

      +27 vendor frames 
  28  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
➜  fias

**Comment by edwardproff** [comment]
Надо поправить connection

 $connection = DB::connection(config('liquetsoft_fias.eloquent_connection'));
        if ($connection instanceof Connection && $connection->getDriverName() === 'mysql') {
            //разбиваем таблицу на части
            $connection->unprepared('ALTER TABLE fias_laravel_room PARTITION BY KEY() PARTITIONS 4;');
        }
