### ISSUE TITLE
[FEATURE] Добавить возможность загружать в базу из файла xml только нужный регион

### ISSUE THREAD

**Issue by wertex** [liquetsoft/fias-laravel#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by marvin255** [comment]
Здравствуйте.

Механизм фильтрации не предусмотрен потому, что он уже встроен в Laravel. Вы можете использовать [декоратор](https://laravel.com/docs/8.x/container#extending-bindings).

Для примера:
1. определите в своем приложении класс для декоратора (**внимание** код не тестировал, но суть раскрывает)
```php
<?php

namespace App;

use Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\Entity\AddressObject;
use Liquetsoft\Fias\Component\Storage\Storage;

class FiasFilterDecorator implements Storage
{
    private $decoratedStorage;

    private $regionToCheck;

    public function __construct(Storage $decoratedStorage, string $regionToCheck)
    {
        $this->decoratedStorage = $decoratedStorage;
        $this->regionToCheck = $regionToCheck;
    }

    public function start(): void
    {
        $this->decoratedStorage->start();
    }

    public function stop(): void
    {
        $this->decoratedStorage->stop();
    }

    public function supports(object $entity): bool
    {
        // помните, что сюда попадут вообще все сущности,
        // предположим мы хотим фильтровать только AddressObject
        if ($entity instanceof AddressObject) {
            return $entity->regioncode === $this->regionToCheck;
        }

        return $this->decoratedStorage->supports($entity);
    }

    public function supportsClass(string $class): bool
    {
        return $this->decoratedStorage->supportsClass($class);
    }

    public function insert(object $entity): void
    {
        $this->decoratedStorage->insert($entity);
    }

    public function delete(object $entity): void
    {
        $this->decoratedStorage->delete($entity);
    }

    public function upsert(object $entity): void
    {
        $this->decoratedStorage->upsert($entity);
    }

    public function truncate(string $entityClassName): void
    {
        $this->decoratedStorage->truncate($entityClassName);
    }
}
```
2. зарегистрируйте этот декоратор в системе, например, в `AppServiceProvider::register`
```php
$this->app->extend(
    \Liquetsoft\Fias\Component\Storage\Storage::class,
    function ($storage, $app) {
        return new FiasFilterDecorator($storage, "код нужного региона");
    }
);
```

Такой вариант позволит вам как угодно фильтровать данные при любом взаимодействии с  базой данных, при этом вы сможете использовать весь доступный в вашем Laravel-приложении функционал.

**Comment by marvin255** [comment]
Я могу подумать про более удобный класс для фильтрации или про filter chain, но на мой взгляд это еще сильнее усложнит и без того сложный код при том, что я все равно не смогу охватить все необходимые случаи фильтрации. Поход с декоратором, на мой взгляд, более гибок и позволяет реализовывать фильтры любой сложности и только те, что необходимы.

**Comment by wertex** [comment]
Спасибо что ответили!

Ранее я применял инструмент, который импортировал данные из dbf. Я так понимаю что в скором времени dbf не будут размещать на сайте, а будет только xml. 
Я попробовал ваш "плагин" и столкнулся с тем, что импортировать в базу весь адресный ряд РФ это очень тяжко... не считая того, что мне необходима только Свердловская область.
Я использовал импорт из папки и за ночь даже половину данных не были загружены :)  даже гигабайта из 38 (кажется) не загрузилось... я понимаю что xml в силу своей структуры имеет больший объем чем sql, гиг из 38... таки очень мало.
В dbf шло разделение на регионы, сейчас этого по всей видимости тоже не будет (хотя изначально  было точно так же... сначала одним файлом все улицы, а потом поделили на регионы)

Сейчас я гружу, а потом вычищаю лишние данные... 

Попробую использовать ваши примеры...
По всей видимости мне проще всего фильтровать по ОКТМО

**Comment by marvin255** [comment]
@wertex попробуйте новую версию 9.0.4. Сейчас затраты времени от чтения текста из файла до передачи модели в eloquent (то есть чистое время обработки в бандле без учена настроек БД и eloquent) составляют не более 0.00035 секунды на одну запись. Как вы понимаете, на настройки БД и на работу eloquent я никак не могу повлиять. Так что вся остальная оптимизация должна быть уже на стороне вашего приложения.
Я попробую выиграть на десериализации объекта, но это будет еще 0.00003...0.00005. Иными словами практически ни на что не повлияет.
