### ISSUE TITLE
[FEATURE] Будет ли обновление ? 

### ISSUE THREAD

**Issue by artemb1393** [liquetsoft/fias-laravel#71]
Будите ли вы обновлять ваш проект так как фиас перестал отправлять ссылки на xml ? Теперь они с Гар работают

**Comment by marvin255** [comment]
Подготовлю релиз. Вроде не так сложно перейти. К сожалению, не смогу потестировать на реальной базе.

**Comment by artemb1393** [comment]
> Подготовлю релиз. Вроде не так сложно перейти. К сожалению, не смогу потестировать на реальной базе.

С нетерпением ждём всей командой ;)

**Comment by marvin255** [comment]
https://github.com/liquetsoft/fias-laravel/releases/tag/v10.0.0 релиз для ГАР.
Тестирование минимальное, но надеюсь, что изменений не так много было.
К сожалению, новый формат совсем отличается, то какого-то плавного перехода не получится. Только полностью удалять старые таблицы и создавать новые. Сущности так же все заменены.

**Comment by artemb1393** [comment]
> https://github.com/liquetsoft/fias-laravel/releases/tag/v10.0.0 релиз для ГАР.
> Тестирование минимальное, но надеюсь, что изменений не так много было.
> К сожалению, новый формат совсем отличается, то какого-то плавного перехода не получится. Только полностью удалять старые таблицы и создавать новые. Сущности так же все заменены.

Увидел . Спасибо большое . В скором времени протестируем ))
