### ISSUE TITLE
[FEATURE] Laravel 9

### ISSUE THREAD

**Issue by toughcookie** [liquetsoft/fias-laravel#77]
При установке на Laravel 9 ругается на
```
liquetsoft/fias-laravel v10.0.0 requires illuminate/database ^6.0|^7.0|^8.0
```
Добавьте, пожалуйста, ^9.0

**Comment by marvin255** [comment]
Попробуйте v11.0.0.

**Comment by toughcookie** [comment]
> Попробуйте v11.0.0.

Спасибо за оперативность!

Но теперь жалуется на 
```
liquetsoft/fias-component v11.0.0 requires psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version)
```

**Comment by marvin255** [comment]
Готовою

**Comment by toughcookie** [comment]
Всё ещё та же ошибка
![image](https://user-images.githubusercontent.com/856162/180758483-4a751a8a-2d17-4c32-bbbb-12e8e4c6e36a.png)

**Comment by marvin255** [comment]
Попробуйте еще раз, пожалуйста, забыл выставить тег в основной библиотеке.

**Comment by toughcookie** [comment]
Всё отлично, установилось. Спасибо!
