### ISSUE TITLE
[FEATURE] Частичная разархивация

### ISSUE THREAD

**Issue by stolentine** [liquetsoft/fias-laravel#81]
Сам архив уже занимает 35ГБ+ а в разархивированном виде еще больше.

Предлагаю для экономии памяти разархивировать не весь архив целиком а по регионам:
1) скачивается архив
2) разархивируется мета инфа
3) вносятся данные в БД
4) очищаются разархивированные данные
5) для каждого региона, который попадает под фильтр:
5.1) разархивируем только один регион
5.2) вносим данные в БД
5.3) очищаем разархивированные данные
6) при завершении очищаем все временные данные

**Comment by liquetsoft** [comment]
Добрый день. Отвечу сразу на все три вопроса тут. К сожалению, ФИАС для моей локации полностью заблокирован. Соответственно, в данный момент поддерживать библиотеку не представляется возможным.

**Comment by stolentine** [comment]
опен сорс на то и опен сорс, что дело одного продолжают другие))
