### ISSUE TITLE
[BUG] Ошибка при вставке AddressObject в БД MS SQL Server

### ISSUE THREAD

**Issue by TssDragon** [liquetsoft/fias-laravel#9]
**Describe the bug**
При первичной установке из директории, во время вставки AddressObject объектов в БД мс скл сервер, на большей части объектов выводится одинаковая ошибка (различаются только сами данные, естественно)
_[2020-05-07 11:21:20] production.ERROR: Error while inserting item of class 'Liquetsoft\Fias\Laravel\LiquetsoftFiasBundle\Entity\AddressObject' to eloquent storage. Item wasn't proceed. {"item":{"aoid":"0f2a8601-40b9-49ce-9fcc-089eccb96a8d","aoguid":"7e005e2b-09ef-4beb-b953-853b999adfa7","parentguid":"ff08620b-ae89-45ab-a1e0-7e7b48b4dd4a","previd":null,"nextid":"a8c16fcf-69fe-4437-9f99-5b46e3a9fe4c","code":"01000001017001201","formalname":"Лесная","offname":"Лесная","shortname":"ул","aolevel":7,"regioncode":"01","areacode":"000","autocode":"0","citycode":"001","ctarcode":"000","placecode":"017","plancode":"0000","streetcode":"0012","extrcode":"0000","sextcode":"000","plaincode":"010000010170012","currstatus":1,"actstatus":0,"livestatus":0,"centstatus":0,"operstatus":1,"ifnsfl":"0105","ifnsul":"0105","terrifnsfl":null,"terrifnsul":null,"okato":"79401000000","oktmo":"79701000","postalcode":"385000","startdate":"1900-01-01 00:00:00","enddate":"2018-09-17 00:00:00","updatedate":"2017-05-05 00:00:00","divtype":0},"error_message":"SQLSTATE[22007]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Преобразование типа данных nvarchar в тип данных datetime привело к выходу значения за пределы диапазона. (SQL: insert into [fias_laravel_address_object] ([actstatus], [aoguid], [aoid], [aolevel], [areacode], [autocode], [centstatus], [citycode], [code], [ctarcode], [currstatus], [divtype], [enddate], [extrcode], [formalname], [ifnsfl], [ifnsul], [livestatus], [nextid], [offname], [okato], [oktmo], [operstatus], [parentguid], [placecode], [plaincode], [plancode], [postalcode], [previd], [regioncode], [sextcode], [shortname], [startdate], [streetcode], [terrifnsfl], [terrifnsul], [updatedate]) values (0, 7e005e2b-09ef-4beb-b953-853b999adfa7, 0f2a8601-40b9-49ce-9fcc-089eccb96a8d, 7, 000, 0, 0, 001, 01000001017001201, 000, 1, 0, 2018-09-17 00:00:00, 0000, Лесная, 0105, 0105, 0, a8c16fcf-69fe-4437-9f99-5b46e3a9fe4c, Лесная, 79401000000, 79701000, 1, ff08620b-ae89-45ab-a1e0-7e7b48b4dd4a, 017, 010000010170012, 0000, 385000, ?, 01, 000, ул, 1900-01-01 00:00:00, 0012, ?, ?, 2017-05-05 00:00:00))"} _
При этом, "ручная" вставка таких объектов в бд проходит без проблем (? заменяются на null)

- win 10 x64
- laravel 7.9.2
- php 7.2 ts x64 + php_rar.dll, php_pdo_sqlsrv_72_ts_x64.dll, php_sqlsrv_72_ts_x64.dll
- ms sql server 14 / ms windows server 2016

**To Reproduce**
1. composer create-project --prefer-dist laravel/laravel fias-updater
2. composer require liquetsoft/fias-laravel
3. php artisan migrate
4. php artisan liquetsoft:fias:install_from_folder D:\fias_xml\

**Comment by marvin255** [comment]
Попробую воспроизвести. На ODBC никогда не проверяли.

**Comment by TssDragon** [comment]
Помогло изменение типа данных в столбцах с датой с  datetime на datetime2.
При этом, "насильное" указание формата даты ( [stackoverflow](https://stackoverflow.com/questions/49999319/error-converting-nvarchar-to-datetime-data-type-using-laravel-and-mssql) и [github/laravel](https://github.com/laravel/framework/issues/27200) не помогало.

**Comment by marvin255** [comment]
Довольно странно, вижу https://github.com/laravel/framework/pull/27911 что тут всё как раз изменено, и должно было попасть в 5.7. В 7 ветке это вот так: https://github.com/laravel/framework/blob/7.x/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L621 - не совсем понятно баг это или фича. Я все же думаю, что это баг и дата должна в одинаковую колонку транслироваться с precision и без.

Я могу указать precision для миграции, но это будет со стороны библиотеки неправильно, да и выглядит как хак.

Предлагаю два варианта:
- запретить библиотеке устанавливать миграции и написать для проекта свои миграции,
- создать issue или pull request сразу в laravel и дождаться новой версии.

Пока закрываю.

**Comment by marvin255** [comment]
Создал на всякий случай дискуссию в репо laravel: https://github.com/laravel/framework/discussions/33049
