### ISSUE TITLE
[BUG] Не обновляется БД

### ISSUE THREAD

**Issue by MaXX527** [liquetsoft/fias-laravel#92]
Последний месяц не обновляются данные, в консоли ошибки:

`php artisan liquetsoft:fias:update
Updating FIAS.

  Something went wrong during the updating. Please check the Laravel's log to get more informati
  on.

In ArrayPipe.php line 145:

  There was an error while running 'Liquetsoft\Fias\Component\Pipeline\Task\CheckStatusTask' tas
  k. Pipeline was interrupted.

In CheckStatusTask.php line 45:

  There are some troubles on the FIAS side. Please try again later.

`
В логах

`[2024-08-06 03:22:39] local.ERROR: There are some troubles on the FIAS side. Please try again later. {"pipeline_class":"Liquetsoft\\Fias\\Component\\Pipeline\\Pipe\\ArrayPipe","pipeline_id":"3395219f-b47f-4475-a416-f8f62a938eae","task":"Liquetsoft\\Fias\\Component\\Pipeline\\Task\\CheckStatusTask","services_statuses":[{"service":"informer","status":"not available","reason":"WSDL file is unavailable"},{"service":"file server","status":"unknown","reason":"Informer is unavailable"}]}
`

**Comment by liquetsoft** [comment]
Исправлено в версии 13.
